import { UserTags } from '@wrcb/cb-common'

export const userTagsLabels: Record<UserTags, string> = {
  [UserTags.Hortifruti]: 'Hortifruti',
  [UserTags.Açougue]: 'Açougue',
  [UserTags.Peixaria]: 'Peixaria',
  [UserTags.Frios]: 'Frios',
  [UserTags.Laticínios]: 'Laticínios',
  [UserTags.Padaria]: 'Padaria',
  [UserTags.Mercearia]: 'Mercearia',
  [UserTags.Congelados]: 'Congelados',
  [UserTags.HigieneEPerfumaria]: 'Higiene e perfumaria',
  [UserTags.Limpeza]: 'Limpeza',
  [UserTags.BebidasAlcoolicas]: 'Bebidas alcoólicas',
  [UserTags.BebidasNaoAlcoolicas]: 'Bebidas não alcoólicas',
  [UserTags.Infantil]: 'Infantil',
  [UserTags.PetShop]: 'Pet shop',
  [UserTags.UtilidadesDomesticas]: 'Utilidades domésticas',

  // =========================
  // 🍔 COMPRANOMIA - FOOD
  // =========================
  [UserTags.Comidas]: 'Comidas',
  [UserTags.Pizzas]: 'Pizzas',
  [UserTags.CachorroQuente]: 'Cachorro-quente',
  [UserTags.Lanches]: 'Lanches',
  [UserTags.Porcoes]: 'Porções',
  [UserTags.Complementos]: 'Complementos',
  [UserTags.Cafeteria]: 'Cafeteria',
  [UserTags.Esfihas]: 'Esfihas',
  [UserTags.Massas]: 'Massas',
  [UserTags.Salgados]: 'Salgados',
  [UserTags.Snacks]: 'Snacks',
  [UserTags.SorvetesECongelados]: 'Sorvetes e congelados',

  // =========================
  // 🥩 COMPRANOMIA - AÇOUGUE
  // =========================
  [UserTags.CarnesBovinas]: 'Carnes bovinas',
  [UserTags.CarnesSuinas]: 'Carnes suínas',
  [UserTags.Aves]: 'Aves',
  [UserTags.CarnesPeixe]: 'Peixes',
  [UserTags.CarnesEspeciais]: 'Carnes especiais',
  [UserTags.EmbutidosEProcessados]: 'Embutidos e processados',
  [UserTags.Churrasco]: 'Churrasco',
  [UserTags.Miudos]: 'Miúdos',

  // =========================
  // 🥬 HORTIFRUTI
  // =========================
  [UserTags.Frutas]: 'Frutas',
  [UserTags.Verduras]: 'Verduras',
  [UserTags.Legumes]: 'Legumes',
  [UserTags.TemperosEErvas]: 'Temperos e ervas',
  [UserTags.Organicos]: 'Orgânicos',
  [UserTags.RaizesETuberculos]: 'Raízes e tubérculos',
  [UserTags.Graos]: 'Grãos',

  // =========================
  // 🐶 PETSHOP
  // =========================
  [UserTags.ComidaCaes]: 'Ração para cães',
  [UserTags.ComidaGatos]: 'Ração para gatos',
  [UserTags.ComidaOutrosAnimais]: 'Ração para outros animais',
  [UserTags.HigieneELimpeza]: 'Higiene e limpeza (pet)',
  [UserTags.BrinquedosEAcessorios]: 'Brinquedos e acessórios',
  [UserTags.Saude]: 'Saúde animal',

  // =========================
  // 🧴 FARMÁCIA
  // =========================
  [UserTags.PetMedicamentos]: 'Medicamentos veterinários',
  [UserTags.PetVidaSaudavel]: 'Vida saudável pet',
  [UserTags.PetHigieneELimpeza]: 'Higiene e limpeza pet',

  [UserTags.PeleCabeloEUnhas]: 'Pele, cabelo e unhas',
  [UserTags.SaudeIntima]: 'Saúde íntima',
  [UserTags.AbsorventesEFraldas]: 'Absorventes e fraldas',
  [UserTags.Antialergicos]: 'Antialérgicos',
  [UserTags.Depilacao]: 'Depilação',
  [UserTags.Banho]: 'Banho',
  [UserTags.HigienePessoal]: 'Higiene pessoal',
  [UserTags.HigieneBucal]: 'Higiene bucal',
  [UserTags.CuidadoMasculino]: 'Cuidados masculinos',
  [UserTags.CuidadoFeminino]: 'Cuidados femininos',
  [UserTags.Repelentes]: 'Repelentes',
  [UserTags.Desodorantes]: 'Desodorantes',
  [UserTags.VitaminasESuplementos]: 'Vitaminas e suplementos',
  [UserTags.Fitness]: 'Fitness',
  [UserTags.Perfumes]: 'Perfumes',
  [UserTags.Maquiagens]: 'Maquiagens',
  [UserTags.Coloracao]: 'Coloração',
  [UserTags.ProtetorSolarEBronzeadores]: 'Protetor solar e bronzeadores',
  [UserTags.HidratantesELimpezaDePele]: 'Hidratantes e limpeza de pele',
  [UserTags.TratamentoCapilar]: 'Tratamento capilar',
  [UserTags.SaudeSexual]: 'Saúde sexual',
  [UserTags.Conveniencia]: 'Conveniência',

  // Medicamentos
  [UserTags.AnticoncepcionaisEDIU]: 'Anticoncepcionais e DIU',
  [UserTags.Antiinflamatorios]: 'Anti-inflamatórios',
  [UserTags.Antidepressivos]: 'Antidepressivos',
  [UserTags.Calmantes]: 'Calmantes',
  [UserTags.Asma]: 'Asma',
  [UserTags.CongestaoNasal]: 'Congestão nasal',
  [UserTags.Diabetes]: 'Diabetes',
  [UserTags.DorEFebre]: 'Dor e febre',
  [UserTags.RiniteESinusite]: 'Rinite e sinusite',
  [UserTags.DorDeGarganta]: 'Dor de garganta',
  [UserTags.GripeEResfriado]: 'Gripe e resfriado',
  [UserTags.ControleDePeso]: 'Controle de peso',
  [UserTags.Gastrite]: 'Gastrite',
  [UserTags.Enxaqueca]: 'Enxaqueca',
  [UserTags.Colesterol]: 'Colesterol',
  [UserTags.Infeccoes]: 'Infecções',
  [UserTags.Insonia]: 'Insônia',
  [UserTags.Tireoide]: 'Tireoide',
  [UserTags.Visao]: 'Visão',
  [UserTags.AziaEMaDigestao]: 'Azia e má digestão',
  [UserTags.PressaoAlta]: 'Pressão alta',
  [UserTags.Tosse]: 'Tosse',
  [UserTags.MedicamentosEspeciais]: 'Medicamentos especiais',

  // Naturais
  [UserTags.Fitoterapicos]: 'Fitoterápicos',
  [UserTags.Homeopatia]: 'Homeopatia',
  [UserTags.RemediosNaturais]: 'Remédios naturais',
  [UserTags.Aromaterapia]: 'Aromaterapia',
  [UserTags.Canabidiol]: 'Canabidiol',

  // Equipamentos
  [UserTags.Inaladores]: 'Inaladores',
  [UserTags.Descartaveis]: 'Descartáveis',
  [UserTags.EquipamentosDeProtecao]: 'Equipamentos de proteção',
  [UserTags.PrimeirosSocorros]: 'Primeiros socorros',
  [UserTags.ContusoesEMachucados]: 'Contusões e machucados',
  [UserTags.Higienizadores]: 'Higienizadores',
  [UserTags.EquipamentosEInstrumentosHospitalares]: 'Equipamentos hospitalares',
  [UserTags.CamasColchoesEAlmofadas]: 'Camas, colchões e almofadas',
  [UserTags.Nebulizadores]: 'Nebulizadores',
  [UserTags.MonitoresETestes]: 'Monitores e testes',
  [UserTags.OrtopedicosEProteses]: 'Ortopédicos e próteses',
  [UserTags.Massageadores]: 'Massageadores',
  [UserTags.Dermocosmeticos]: 'Dermocosméticos',
  [UserTags.Nutricosmeticos]: 'Nutricosméticos',

  // Bebê
  [UserTags.PeleDoBebe]: 'Pele do bebê',
  [UserTags.BanhoDoBebe]: 'Banho do bebê',
  [UserTags.Amamentacao]: 'Amamentação',
  [UserTags.AlimentacaoDoBebe]: 'Alimentação do bebê',

  // =========================
  // 🌾 AGROPECUÁRIA
  // =========================
  [UserTags.Gado]: 'Gado',
  [UserTags.AvesAgropecuaria]: 'Aves',
  [UserTags.Equinos]: 'Equinos',
  [UserTags.Suinos]: 'Suínos',
  [UserTags.Jardinagem]: 'Jardinagem',
  [UserTags.Defensivos]: 'Defensivos agrícolas',
  [UserTags.Ferramentas]: 'Ferramentas',
  [UserTags.Caes]: 'Cães',
  [UserTags.Gatos]: 'Gatos',

  // =========================
  // 🔧 SERVIÇOS
  // =========================
  [UserTags.LimpezaAutomotiva]: 'Limpeza automotiva',

  // =========================
  // 💧 ÁGUA E GÁS
  // =========================
  [UserTags.Agua]: 'Água',
  [UserTags.Gas]: 'Gás',

  // =========================
  // OUTROS
  // =========================
  [UserTags.Outros]: 'Outros',

  [UserTags.CityTour]: '',
  [UserTags.CulturalTour]: '',
  [UserTags.GastronomicTour]: '',
  [UserTags.AdventureTour]: '',
  [UserTags.HistoricalTour]: '',
  [UserTags.NatureTour]: '',
  [UserTags.ReligiousTour]: '',
  [UserTags.ShoppingTour]: '',
  [UserTags.AquaticTour]: '',
  [UserTags.Photographer]: '',
  [UserTags.BrazilianLanguage]: '',
  [UserTags.SpanishLanguage]: '',
  [UserTags.EnglishLanguage]: '',
  [UserTags.FrenchLanguage]: '',
  [UserTags.ItalianLanguage]: '',
  [UserTags.Brazilian]: '',
  [UserTags.Italian]: '',
  [UserTags.Japanese]: '',
  [UserTags.Chinese]: '',
  [UserTags.FastFood]: '',
  [UserTags.LocalFood]: '',
  [UserTags.Mexican]: '',
  [UserTags.Arabic]: '',
  [UserTags.French]: '',
  [UserTags.Indian]: '',
  [UserTags.Mediterranean]: '',
  [UserTags.Vegetarian]: '',
  [UserTags.Air]: '',
  [UserTags.Sea]: '',
  [UserTags.Land]: '',
  [UserTags.Pop]: '',
  [UserTags.Rock]: '',
  [UserTags.Electronic]: '',
  [UserTags.Samba]: '',
  [UserTags.Sertanejo]: '',
  [UserTags.Forro]: '',
  [UserTags.Funk]: '',
  [UserTags.MPB]: '',
  [UserTags.CulturalFestival]: '',
  [UserTags.MusicEvent]: '',
  [UserTags.SportsEvent]: '',
  [UserTags.GastronomicEvent]: '',
  [UserTags.FairAndExhibition]: '',
  [UserTags.ReligiousEvent]: '',
  [UserTags.CorporateEvent]: '',
  [UserTags.FashionAndBeautyEvent]: '',
  [UserTags.FamilyAndKidsEvent]: '',
  [UserTags.AdventureAndEcoTourismEvent]: '',
  [UserTags.Anal]: '',
  [UserTags.Arab]: '',
  [UserTags.ASMR]: '',
  [UserTags.Asian]: '',
  [UserTags.Athletic]: '',
  [UserTags.BBW]: '',
  [UserTags.BDSM]: '',
  [UserTags.Black]: '',
  [UserTags.Blonde]: '',
  [UserTags.Brunette]: '',
  [UserTags.Cosplay]: '',
  [UserTags.Cuckold]: '',
  [UserTags.Curvy]: '',
  [UserTags.Dancing]: '',
  [UserTags.DirtyTalk]: '',
  [UserTags.Domination]: '',
  [UserTags.DP]: '',
  [UserTags.Ebony]: '',
  [UserTags.Feet]: '',
  [UserTags.Findom]: '',
  [UserTags.Fingering]: '',
  [UserTags.Gamer]: '',
  [UserTags.GILF]: '',
  [UserTags.Group]: '',
  [UserTags.Hairy]: '',
  [UserTags.InteractiveToys]: '',
  [UserTags.JOI]: '',
  [UserTags.Latina]: '',
  [UserTags.Lactating]: '',
  [UserTags.Maid]: '',
  [UserTags.Mature]: '',
  [UserTags.MILF]: '',
  [UserTags.Muscle]: '',
  [UserTags.Natural]: '',
  [UserTags.Nurse]: '',
  [UserTags.Nympho]: '',
  [UserTags.OilShow]: '',
  [UserTags.Oral]: '',
  [UserTags.Outdoor]: '',
  [UserTags.Petite]: '',
  [UserTags.Pierced]: '',
  [UserTags.Pregnant]: '',
  [UserTags.Redhead]: '',
  [UserTags.Roleplay]: '',
  [UserTags.Secretary]: '',
  [UserTags.Shaved]: '',
  [UserTags.Shower]: '',
  [UserTags.ShowerShow]: '',
  [UserTags.Slim]: '',
  [UserTags.Smoking]: '',
  [UserTags.SPH]: '',
  [UserTags.Squirt]: '',
  [UserTags.Striptease]: '',
  [UserTags.Student]: '',
  [UserTags.Submission]: '',
  [UserTags.Tattooed]: '',
  [UserTags.Teacher]: '',
  [UserTags.Teen18Plus]: '',
  [UserTags.Toys]: '',
  [UserTags.Voyeur]: '',
  [UserTags.White]: '',
}

export function sortByLabel<T extends string>(
  values: T[],
  labels: Record<T, string>,
): T[] {
  return [...values].sort((a, b) =>
    (labels[a] ?? a).localeCompare(labels[b] ?? b, 'pt-BR'),
  )
}
